baseURL: https://pokernotes.ivkin.dev/
languageCode: en-us
title: Live Poker Notes
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description: Quickly write your live poker hands history on your watch
  # Preloader ensures images are loaded before displaying to the user. If you don't want it uncomment to set it to false
  # preloader: false
  navbarlogo:
  # Logo (from static/images/logos/___)
    image:
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Live Poker Notes
    # Hero subtitle (optional)
    subtitle: Quickly write your live poker hands history right at the table without distraction
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "https://forms.gle/Dvp9UjuUHJdizuub7"
    # Hero image (from static/images/___)
    image: illustrations/poker-watch.gif
    # Footer logos (from static/images/logos/clients/___.svg)
    # clientlogos:
    # - systek
    # - tribe
    # - kromo
    # - infinite
    # - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.

  
  # section1:
  #   title: Great power comes
  #   subtitle: with great responsibility
  #   tiles:
  #   - title: App builder
  #     icon: mouse-globe
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Free trial
  #   - title: Cloud integration
  #     icon: laptop-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started
  #   - title: Add-ons & plugins
  #     icon: plug-cloud
  #     text: This is some explanatory text that is on two rows
  #     url: /
  #     buttonText: Get started
  section2:
    title: Raise your game to the next level
    subtitle: and win more hands
    features:
    - title: At your fingertips
      text: Make a note with just a few taps
      icon: fingertips
    - title: Record while playing
      text: Make a note right at the table without any distraction
      icon: record
    - title: Learn
      text: Analyze your desicions and fix mistakes
      icon: learn
  # section3:
  #   title: One platform
  #   subtitle: To rule them all
  #   image: illustrations/mockups/app-mockup.png
  #   buttonText: Get started
  #   buttonLink: "#"
  # section4:
  #   title: Our Clients love us!
  #   subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
  #   clients:
  #   - name: Irma Walters
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Accountant
  #     img: 1
  #   - name: John Bradley
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: Financial Analyst
  #     img: 2
  #   - name: Gary Blackman
  #     quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
  #     job: HR Manager
  #     img: 3
  # section5: true
  footer:
    # Logo (from /images/logos/___)
#    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://instagram.com/#
      icon: instagram    
    bulmalogo: false
    quicklinks:
      # column1:
      #   title: "Product"
      #   links:
      #   - text: Discover features
      #     link: /
      #   - text: Why choose our product?
      #     link: /
      #   - text: Compare features
      #     link: /
      #   - text: Our roadmap
      #     link: /
      #   - text: AGB
      #     link: /agb
      # column2:
      #   title: "Docs"
      #   links:
      #   - text: Get started
      #     link: /
      #   - text: User guides
      #     link: /
      #   - text: Admin guide
      #     link: /
      #   - text: Developers
      #     link: /
      # column3:
      #   title: "Blog"
      #   links:
      #   - text: Latest news
      #     link: /blog/first
      #   - text: Tech articles
      #     link: /blog/second
